default_zlib_version="1.3.1"
default_nginx_version="1.20.2"
default_njs_version="0.7.2"
default_modsecurity_version="3.0.14"
default_modsecurity_nginx_version="1.0.3"
default_modsecurity_coreruleset_version="4.13.0"
